/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiCluedo.ui;

/**
 *
 * @author James
 */
public class startScreen extends javax.swing.JFrame {
public int numberOPlayers = 0;
    /**
     * Creates new form startScreen
     */
    public startScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPlayers = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        okNumPlayers = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        numPLayers = new javax.swing.JComboBox();
        donePlayerSetup = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        playerName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        missScarlett = new javax.swing.JRadioButton();
        profPlum = new javax.swing.JRadioButton();
        mrsWhite = new javax.swing.JRadioButton();
        colonelMustard = new javax.swing.JRadioButton();
        revGreen = new javax.swing.JRadioButton();
        mrsPeacock = new javax.swing.JRadioButton();
        colourRed = new javax.swing.JRadioButton();
        coulourBlue = new javax.swing.JRadioButton();
        colourYellow = new javax.swing.JRadioButton();
        colourPurple = new javax.swing.JRadioButton();
        colourWhite = new javax.swing.JRadioButton();
        colourGreen = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setPlayers.setAlwaysOnTop(true);
        setPlayers.setMinimumSize(new java.awt.Dimension(400, 200));

        jLabel2.setText("How many players?");

        okNumPlayers.setText("OK");
        okNumPlayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okNumPlayersActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Welcome to Cluedo!");

        numPLayers.setMaximumRowCount(5);
        numPLayers.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4", "5", "6" }));
        numPLayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPLayersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout setPlayersLayout = new javax.swing.GroupLayout(setPlayers.getContentPane());
        setPlayers.getContentPane().setLayout(setPlayersLayout);
        setPlayersLayout.setHorizontalGroup(
            setPlayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setPlayersLayout.createSequentialGroup()
                .addGroup(setPlayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(setPlayersLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel6))
                    .addGroup(setPlayersLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(okNumPlayers))
                    .addGroup(setPlayersLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(setPlayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numPLayers, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        setPlayersLayout.setVerticalGroup(
            setPlayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setPlayersLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(numPLayers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(okNumPlayers)
                .addGap(23, 23, 23))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        donePlayerSetup.setText("Done");
        donePlayerSetup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donePlayerSetupActionPerformed(evt);
            }
        });

        jLabel1.setText("You name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("Player Selection");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Character:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Colour:");

        missScarlett.setText("Miss Scarlett");
        missScarlett.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                missScarlettActionPerformed(evt);
            }
        });

        profPlum.setText("Professor Plum");

        mrsWhite.setText("Mrs. White");
        mrsWhite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrsWhiteActionPerformed(evt);
            }
        });

        colonelMustard.setText("Colonel Mustard");

        revGreen.setText("The Reverend Green");

        mrsPeacock.setText("Mrs. Peacock");

        colourRed.setText("Red");

        coulourBlue.setText("Blue");

        colourYellow.setText("Yellow");
        colourYellow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colourYellowActionPerformed(evt);
            }
        });

        colourPurple.setText("Purple");

        colourWhite.setText("White");

        colourGreen.setText("Green");

        jButton1.setText("Set # Players");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(donePlayerSetup, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(playerName, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(253, 253, 253)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(revGreen)
                                        .addComponent(missScarlett, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(mrsPeacock, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(mrsWhite)
                                    .addComponent(profPlum)
                                    .addComponent(colonelMustard))
                                .addGap(187, 187, 187)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(colourRed)
                                    .addComponent(coulourBlue)
                                    .addComponent(colourYellow)
                                    .addComponent(colourPurple)
                                    .addComponent(colourWhite)
                                    .addComponent(colourGreen))))))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(playerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(missScarlett)
                    .addComponent(colourRed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profPlum)
                    .addComponent(colourGreen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mrsWhite)
                    .addComponent(coulourBlue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colonelMustard)
                    .addComponent(colourYellow))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(revGreen)
                    .addComponent(colourPurple))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mrsPeacock)
                    .addComponent(colourWhite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(donePlayerSetup, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okNumPlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okNumPlayersActionPerformed
      setPlayers.setVisible(false);
    }

    private void donePlayerSetupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donePlayerSetupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_donePlayerSetupActionPerformed

    private void missScarlettActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_missScarlettActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_missScarlettActionPerformed

    private void mrsWhiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrsWhiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mrsWhiteActionPerformed

    private void colourYellowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colourYellowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colourYellowActionPerformed

    private void numPLayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPLayersActionPerformed
        //numberOPlayers = numPLayers.getSelectedItem().toString();
        System.out.println(numPLayers.getSelectedItem());
    }//GEN-LAST:event_numPLayersActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         setPlayers.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(startScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(startScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(startScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(startScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new startScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton colonelMustard;
    private javax.swing.JRadioButton colourGreen;
    private javax.swing.JRadioButton colourPurple;
    private javax.swing.JRadioButton colourRed;
    private javax.swing.JRadioButton colourWhite;
    private javax.swing.JRadioButton colourYellow;
    private javax.swing.JRadioButton coulourBlue;
    private javax.swing.JButton donePlayerSetup;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton missScarlett;
    private javax.swing.JRadioButton mrsPeacock;
    private javax.swing.JRadioButton mrsWhite;
    private javax.swing.JComboBox numPLayers;
    private javax.swing.JButton okNumPlayers;
    private javax.swing.JTextField playerName;
    private javax.swing.JRadioButton profPlum;
    private javax.swing.JRadioButton revGreen;
    private javax.swing.JDialog setPlayers;
    // End of variables declaration//GEN-END:variables
}
