/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiCluedo.ui;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

import javax.swing.ButtonGroup;

import guiCluedo.game.Board;
import guiCluedo.game.Player;

/**
 *
 * @author James
 */
public class startScreen extends javax.swing.JFrame {
	public int numberOPlayers = 2;
	private int counter;
	public static ArrayList<Player> players = new ArrayList<Player>();
	private ArrayList<String> chars = new ArrayList<>(Arrays.asList("Miss Scarlett", "Colonel Mustard","Mrs. White", "The Reverend Green", "Mrs. Peacock", "Professor Plum"));
	private ArrayList<String> iColours = new ArrayList<>(Arrays.asList("Red", "Green", "Blue", "White", "Yellow", "Purple"));
	private ButtonGroup characterRadios = new ButtonGroup();
	private ButtonGroup colourRadios = new ButtonGroup();
	/**
	 * Creates new form startScreen
	 */
	public startScreen() {
		initComponents();
		
		//Create button groups
		characterRadios.add(missScarlett);
		characterRadios.add(mrsPeacock);
		characterRadios.add(profPlum);
		characterRadios.add(mrsWhite);
		characterRadios.add(revGreen);
		characterRadios.add(colonelMustard);
		
		colourRadios.add(colourBlue);
		colourRadios.add(colourGreen);
		colourRadios.add(colourPurple);
		colourRadios.add(colourRed);
		colourRadios.add(colourWhite);
		colourRadios.add(colourYellow);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPlayers = new javax.swing.JDialog();
        setPHowManyText = new javax.swing.JLabel();
        okNumPlayers = new javax.swing.JButton();
        setPHeadText = new javax.swing.JLabel();
        numPLayers = new javax.swing.JComboBox();
        warning = new javax.swing.JDialog();
        warningTextHead = new javax.swing.JLabel();
        warningOk = new javax.swing.JButton();
        warningLine1 = new javax.swing.JLabel();
        warningLine2 = new javax.swing.JLabel();
        donePlayerSetup = new javax.swing.JButton();
        mainYNameTxt = new javax.swing.JLabel();
        playerName = new javax.swing.JTextField();
        selectionHeadText = new javax.swing.JLabel();
        charSubCatTxt = new javax.swing.JLabel();
        colourSubTxt = new javax.swing.JLabel();
        missScarlett = new javax.swing.JRadioButton();
        profPlum = new javax.swing.JRadioButton();
        mrsWhite = new javax.swing.JRadioButton();
        colonelMustard = new javax.swing.JRadioButton();
        revGreen = new javax.swing.JRadioButton();
        mrsPeacock = new javax.swing.JRadioButton();
        colourRed = new javax.swing.JRadioButton();
        colourBlue = new javax.swing.JRadioButton();
        colourYellow = new javax.swing.JRadioButton();
        colourPurple = new javax.swing.JRadioButton();
        colourWhite = new javax.swing.JRadioButton();
        colourGreen = new javax.swing.JRadioButton();
        setPlayersButton = new javax.swing.JButton();

        setPlayers.setAlwaysOnTop(true);
        setPlayers.setMinimumSize(new java.awt.Dimension(400, 200));

        setPHowManyText.setText("How many players?");

        okNumPlayers.setText("OK");
        okNumPlayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okNumPlayersActionPerformed(evt);
            }
        });

        setPHeadText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        setPHeadText.setText("Welcome to Cluedo!");

        numPLayers.setMaximumRowCount(5);
        numPLayers.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4", "5", "6" }));
        numPLayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPLayersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout setPlayersLayout = new javax.swing.GroupLayout(setPlayers.getContentPane());
        setPlayers.getContentPane().setLayout(setPlayersLayout);
        setPlayersLayout.setHorizontalGroup(
            setPlayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setPlayersLayout.createSequentialGroup()
                .addGroup(setPlayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(setPlayersLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(setPHeadText))
                    .addGroup(setPlayersLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(okNumPlayers))
                    .addGroup(setPlayersLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(setPlayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(setPHowManyText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numPLayers, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        setPlayersLayout.setVerticalGroup(
            setPlayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setPlayersLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(setPHeadText)
                .addGap(18, 18, 18)
                .addComponent(setPHowManyText)
                .addGap(18, 18, 18)
                .addComponent(numPLayers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(okNumPlayers)
                .addGap(23, 23, 23))
        );

        warningTextHead.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        warningTextHead.setText("WARNING!");

        warningOk.setText("OK");
        warningOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warningOkActionPerformed(evt);
            }
        });

        warningLine1.setText("Make sure that you have selected one from character and one from colour and only one");

        warningLine2.setText("Make sure that you have alos entered your name");

        javax.swing.GroupLayout warningLayout = new javax.swing.GroupLayout(warning.getContentPane());
        warning.getContentPane().setLayout(warningLayout);
        warningLayout.setHorizontalGroup(
            warningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(warningLayout.createSequentialGroup()
                .addGroup(warningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(warningLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(warningTextHead))
                    .addGroup(warningLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(warningLine1))
                    .addGroup(warningLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(warningOk, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(warningLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(warningLine2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        warningLayout.setVerticalGroup(
            warningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(warningLayout.createSequentialGroup()
                .addComponent(warningTextHead)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warningLine1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(warningLine2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(warningOk)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        donePlayerSetup.setText("Done");
        donePlayerSetup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donePlayerSetupActionPerformed(evt);
            }
        });

        mainYNameTxt.setText("You name:");

        selectionHeadText.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        selectionHeadText.setText("Player Selection");

        charSubCatTxt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        charSubCatTxt.setText("Character:");

        colourSubTxt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        colourSubTxt.setText("Colour:");

        missScarlett.setText("Miss Scarlett");
        missScarlett.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                missScarlettActionPerformed(evt);
            }
        });

        profPlum.setText("Professor Plum");

        mrsWhite.setText("Mrs. White");
        mrsWhite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mrsWhiteActionPerformed(evt);
            }
        });

        colonelMustard.setText("Colonel Mustard");

        revGreen.setText("The Reverend Green");

        mrsPeacock.setText("Mrs. Peacock");

        colourRed.setText("Red");

        colourBlue.setText("Blue");

        colourYellow.setText("Yellow");
        colourYellow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colourYellowActionPerformed(evt);
            }
        });

        colourPurple.setText("Purple");

        colourWhite.setText("White");

        colourGreen.setText("Green");

        setPlayersButton.setText("Set # Players");
        setPlayersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setPlayersButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(donePlayerSetup, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(mainYNameTxt)
                        .addGap(18, 18, 18)
                        .addComponent(playerName, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(setPlayersButton)
                        .addGap(42, 42, 42)
                        .addComponent(selectionHeadText))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(charSubCatTxt)
                                .addGap(253, 253, 253)
                                .addComponent(colourSubTxt))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(revGreen)
                                        .addComponent(missScarlett, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(mrsPeacock, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(mrsWhite)
                                    .addComponent(profPlum)
                                    .addComponent(colonelMustard))
                                .addGap(187, 187, 187)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(colourRed)
                                    .addComponent(colourBlue)
                                    .addComponent(colourYellow)
                                    .addComponent(colourPurple)
                                    .addComponent(colourWhite)
                                    .addComponent(colourGreen))))))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectionHeadText)
                    .addComponent(setPlayersButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainYNameTxt)
                    .addComponent(playerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(charSubCatTxt)
                    .addComponent(colourSubTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(missScarlett)
                    .addComponent(colourRed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profPlum)
                    .addComponent(colourGreen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mrsWhite)
                    .addComponent(colourBlue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colonelMustard)
                    .addComponent(colourYellow))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(revGreen)
                    .addComponent(colourPurple))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mrsPeacock)
                    .addComponent(colourWhite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(donePlayerSetup, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void okNumPlayersActionPerformed(java.awt.event.ActionEvent evt) {                                             
		String p = (String)numPLayers.getSelectedItem();
		if(p.equals("2"))
		{
			numberOPlayers = 2;
		}
		else if(p.equals("3"))
		{
			numberOPlayers = 3;
		}
		else if(p.equals("4"))
		{
			numberOPlayers = 4;
		}
		else if(p.equals("5"))
		{
			numberOPlayers = 5;
		}
		else if(p.equals("6"))
		{
			numberOPlayers = 6;
		}
		else
		{
			numberOPlayers = 2;
		}

		System.out.println(numberOPlayers);
		setPlayers.setVisible(false);
	}

	private void donePlayerSetupActionPerformed(java.awt.event.ActionEvent evt) {                                                
//		String pName = "";
//		if(playerName.getText() != "")
//		{
//			pName = playerName.getText();
//		}
//		else
//		{
//			warning.setVisible(true);
//		}
//		String cCharacter = "";
//		System.out.println(pName);
//		
//		cCharacter = getCharacter();
//		if(!cCharacter.equals("")){
//		 System.out.println("Character was: " + cCharacter);
//		}
//		else
//		{
//			System.out.println("Please select a character");
//			warning.setVisible(true);
//			cCharacter = getCharacter();
//			return;
//		}
//		String cColour = getColour();
//		if(!cColour.equals(""))
//		{
//			System.err.println("Colour was: " + cColour);
//		}
//		else
//		{
//			System.out.println("Please select a colour");
//			warning.setVisible(true);
//			cColour = getColour();
//			return;
//		}
//		Player p = new Player(pName, cCharacter, cColour, counter);
//		iColours.remove(cColour);
//		chars.remove(cCharacter);
//		System.out.println("Player created!");
//		players.add(p);
//		System.out.println("PlayerF added");
//		colourRadios.clearSelection();
//		characterRadios.clearSelection();
//		playerName.setText("");

		Player p = new Player("Cam", "Cool guy", "Red", 1);
		players.add(p);
		Player p1 = new Player("James", "Lame guy", "Blue", 2);
		players.add(p1);
		

		counter++;
		if(counter >= numberOPlayers )
		{
			System.out.println("Go to main game screen");
			//Launch UI
			new UI().setVisible(true);
			this.setVisible(false);//Hide the player setup screen
			return;

		}
	}

	private String getColour() {
		if(colourRed.isSelected())
		{
			if(iColours.contains("Red")){
				return "Red";
			}
			//Display error message, ask user to choose something else as this has already been chosen	
		}
		else if(colourGreen.isSelected())
		{
			if(iColours.contains("Green")){;
				return "Green";
			}
			//Display error message	
		}
		else if(colourBlue.isSelected())
		{
			if(iColours.contains("Blue")){
				return "Blue";
			}
			//Display error message		
		}
		else if(colourYellow.isSelected())
		{
			if(iColours.contains("Yellow")){
				return "Yellow";
			}
			//Display error message		
		}
		else if(colourWhite.isSelected())
		{
			if(iColours.contains("White")){
				return "White";
			}
			//Display error message		
		}
		else if(colourPurple.isSelected())
		{
			if(iColours.contains("Purple")){
				return "Purple";
			}
			//Display error message		
		}
		return "";
	}

	private String getCharacter() {
		if(colonelMustard.isSelected())
		{
			String character = "Colonel Mustard";
			if(chars.contains(character)){
				return character;
			}
			//Display error message	
		}
		else if(missScarlett.isSelected())
		{
			String character = "Miss Scarlett";
			if(chars.contains(character)){
				return character;
			}
			//Display error message	
		}
		else if(mrsPeacock.isSelected())
		{
			String character = "Mrs. Peacock";
			if(chars.contains(character)){
				return character;
			}
			//Display error message	
		}
		else if(mrsWhite.isSelected())
		{
			String character = "Mrs. White";
			if(chars.contains(character)){
				return character;
			}
			//Display error message	
		}
		else if(profPlum.isSelected())
		{
			String character = "Professor Plum";
			if(chars.contains(character)){
				return character;
			}
			//Display error message	
		}
		else if(revGreen.isSelected())
		{
			String character = "The Reverend Green";
			if(chars.contains(character)){
				return character;
			}
			//Display error message	
		}
		return "";
	}

	private void missScarlettActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_missScarlettActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_missScarlettActionPerformed

	private void mrsWhiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mrsWhiteActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_mrsWhiteActionPerformed

	private void colourYellowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colourYellowActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_colourYellowActionPerformed

	private void numPLayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPLayersActionPerformed

	}//GEN-LAST:event_numPLayersActionPerformed

	private void setPlayersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setPlayersButtonActionPerformed

		setPlayers.setVisible(true);
	}//GEN-LAST:event_setPlayersButtonActionPerformed

    private void warningOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warningOkActionPerformed
        warning.setVisible(false);
    }//GEN-LAST:event_warningOkActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(startScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(startScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(startScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(startScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new startScreen().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel charSubCatTxt;
    private javax.swing.JRadioButton colonelMustard;
    private javax.swing.JRadioButton colourBlue;
    private javax.swing.JRadioButton colourGreen;
    private javax.swing.JRadioButton colourPurple;
    private javax.swing.JRadioButton colourRed;
    private javax.swing.JLabel colourSubTxt;
    private javax.swing.JRadioButton colourWhite;
    private javax.swing.JRadioButton colourYellow;
    private javax.swing.JButton donePlayerSetup;
    private javax.swing.JLabel mainYNameTxt;
    private javax.swing.JRadioButton missScarlett;
    private javax.swing.JRadioButton mrsPeacock;
    private javax.swing.JRadioButton mrsWhite;
    private javax.swing.JComboBox numPLayers;
    private javax.swing.JButton okNumPlayers;
    private javax.swing.JTextField playerName;
    private javax.swing.JRadioButton profPlum;
    private javax.swing.JRadioButton revGreen;
    private javax.swing.JLabel selectionHeadText;
    private javax.swing.JLabel setPHeadText;
    private javax.swing.JLabel setPHowManyText;
    private javax.swing.JDialog setPlayers;
    private javax.swing.JButton setPlayersButton;
    private javax.swing.JDialog warning;
    private javax.swing.JLabel warningLine1;
    private javax.swing.JLabel warningLine2;
    private javax.swing.JButton warningOk;
    private javax.swing.JLabel warningTextHead;
    // End of variables declaration//GEN-END:variables
}
